apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
        - name: streamlit
          image: your-docker-image  # Replace with your image name, e.g., streamlit:latest
          ports:
            - containerPort: 8503
          resources:
            limits:
              memory: "1Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: OPENAI_API_KEY
            - name: PINECONE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: api-keys
                  key: PINECONE_API_KEY
            - name: PINECONE_ENVIRONMENT
              value: "us-east-1"
            - name: INDEX_NAME
              value: "canopy--langchain"
            - name: NAMESPACE
              value: "test-1"

---
apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
spec:
  type: LoadBalancer
  ports:
    - port: 8503
      targetPort: 8503
  selector:
    app: streamlit
---
apiVersion: v1
kind: Secret
metadata:
  name: api-keys
type: Opaque
data:
  OPENAI_API_KEY: <base64_encoded_openai_api_key>
  PINECONE_API_KEY: <base64_encoded_pinecone_api_key>
